# AUTO-GENERATED by install.sh — STARTER. Edit sesuai kebutuhan (ext PHP, db, dll).
FROM php:8.4-fpm-alpine

# Install system dependencies
RUN apk add --no-cache \
    libpng-dev libzip-dev freetype-dev libjpeg-turbo-dev \
    oniguruma-dev libxml2-dev curl git unzip

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath xml zip gd opcache

# Set upload limits to prevent entity too large issues
RUN echo "upload_max_filesize = 20M" > /usr/local/etc/php/conf.d/uploads.ini \
    && echo "post_max_size = 20M" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "memory_limit = 256M" >> /usr/local/etc/php/conf.d/uploads.ini

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copy composer files first for better Docker layer caching
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-scripts

# Copy the rest of the application
COPY --chown=www-data:www-data . .

# Run post-install scripts (laravel package:discover, etc.)
RUN composer dump-autoload --optimize \
    && php artisan package:discover --ansi || true

# Set proper permissions for Laravel
RUN chown -R www-data:www-data storage bootstrap/cache \
    && chmod -R 775 storage bootstrap/cache
